### ISSUE TITLE
"Cannot autolaunch D-Bus without X11 $DISPLAY"

### ISSUE THREAD

**Issue by allefeld** [sirjmann92/nicotineplus-proper#18]
In the Docker output, I get many warning messages with the same text,
`(org.nicotine_plus.Nicotine:41): dconf-WARNING **: 18:21:45.614: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY`
This doesn't seem to affect function though.

Thanks for the image btw.!

**Comment by sirjmann92** [comment]
This is usually a permissions issue. Which image tag are you using, and can you share your run/Compose script (redact anything sensitive).

**Comment by sirjmann92** [comment]
I'm using a very similar setup, but I use AirVPN and I use a forwarded port that I setup in my client area of the AirVPN portal, so I don't need to open a port on my router. If PIA supports forwarding, you could do the same and you wouldn't need to manually deal with ports other than defining them in your containers. If it doesn't, you could always define a port in your gluetun container for the port of your choice (e.g. 12345) and then use port 12345 in your N+ config and you may need to open it on your router. Once defined and set, you shouldn't need to fiddle with it.

As far as your config, the only thing that I can see that's different than intended is the data directory is not below the config directory. That probably wouldn't make a difference UNLESS you didn't create either directory manually before you started the container (or with the 1000:1000 user that you've defined in your config). If you didn't create them before spinning up the container, then they would be created as root (because that's how Docker does it) and then the application runs as a user that you define (1000:1000 in your case, based on your PUID and PGID).

You could try stopping your container, removing the image, delete the config and data directories, create the config directory from the 1000:1000 user ( /home/ca/Store/nicotine/config ) then create the data directory from the 1000:1000 user ( /home/ca/Store/nicotine/config/data ), then start your container.

I've seen those errors before, and it's usually when I'm dealing with users and permissions. Also, please double check your user and group assignments by running "id" in a terminal and make sure your PUID/PGID are set correctly.

Here's my compose file (ports, IPs, and other info edited):
```
services:
  nicotineplus-proper:
    image: sirjmann92/nicotineplus-proper:test
    container_name: nicotine
    network_mode: "service:gluetun"
    env_file: nicotine.env
    cpus: '4'
    volumes:
      - /home/jase/docker/nicotine/config:/config
      - /home/jase/docker/nicotine/config/data:/data
      - /mnt/NASferatu:/share:rw
      - /mnt/NAStradamus:/share-exp:rw
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
  
  deluge:
    image: lscr.io/linuxserver/deluge:2.1.1-r10-ls323
    container_name: deluge
    network_mode: "service:gluetun"
    cpus: '6'
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:deluge
      - TP_THEME=overseerr #Options aquamarine hotline hotpink dracula dark organizr space-gray overseerr plex nord maroon
    volumes:
      - /home/jase/docker/deluge/config:/config:rw
      - /mnt/Data/Downloads:/torrent-dl:rw
      - /home/jase/Downloads:/downloads:rw
      - /mnt/NASferatu:/share:rw
      - /mnt/NAStradamus:/share-exp:rw
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      olympus:
        ipv4_address: 1.1.0.2

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    network_mode: "service:gluetun"
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/jase/docker/firefox/config:/config
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    env_file: gluetun.env
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/jase/docker/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: always
    ports:
      - 11111:11111# Firefox
      - 22222:22222# Deluge
      - 33333:33333# Deluge WebUI
      - 44444:44444# Nicotine+ WebUI 
      - 55555:55555# AirVPN Forward Port
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
    networks:
      olympus:
        ipv4_address: 1.1.0.1

networks:
  olympus:
    name: olympus
    external: true
```
