### ISSUE TITLE
how to set forwarded port from VPN provider?

### ISSUE THREAD

**Issue by phirestalker** [sirjmann92/nicotineplus-proper#19]
You mention that you use a VPN and use their forwarded port. I also have a VPN and wish to use their forwarded port, but I can't find in the documentation how to set this port. I know I can set it in the interface, but my VPN gives me a random port, so I need to set it every time the container comes up. What do you use to do this?

**Comment by phirestalker** [comment]
I was able to use the gluetun functionality to write a .env file with the random port, then I used the test tag and it successfully set the listening port. Thanks. Now to test.

**Comment by phirestalker** [comment]
Just for anyone else, here is what I did.

I used this line under environment section of gluetun service to create a .env file (remember this is a path inside the gluetun container, so plan accordingly)
`- VPN_PORT_FORWARDING_UP_COMMAND=sh -c 'echo "LISTEN_AT={{PORTS}}" > /config/.env'`

I then used the new env variable
`- FORWARD_PORT=${LISTEN_AT}`

I then created my own healthcheck for the gluetun service, as the one built in shows healthy status before the forwarded_port file is even created most times.
```
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/gluetun/forwarded_port"]
      start_period: 20s
```
Now, when I make this service depend on a healthy status of gluetun, it will have a forwarded port before starting.

@sirjmann92, Just for curiosity, when will these changes be on latest, so I can move back to the safer image?

**Comment by sirjmann92** [comment]
@phirestalker , I'm glad it helped and good job figuring it out. Thanks for posting your solution for others.

I'll give it a few days to a week soak and then get it moved over. Let me know if you experience any oddities with the new image in the meantime.

**Comment by phirestalker** [comment]
Ugh, it only worked once. The timing is not right. Docker likes to read the compose file and load the environment of nicotine before gluetun is healthy and the forwarded_port file is created. Then, it will wait until the file is there to START the container, but the damage is already done. I am still working on this. I already have a custom entry point script I am trying for nicotine, but not sure what to try next.

**Comment by phirestalker** [comment]
Could you provide the sed line you added for the new environment variable? I want to try to do that myself, but with the latest tag, and see if I can type again.

**Comment by phirestalker** [comment]
Alright, here is the updated config that actually works

custom entrypoint
```
#!/bin/bash
set -e # Exit immediately if a command exits with a non-zero status.

# --- Configuration ---
# Define the path to the file that must exist before starting Nicotine+.
# This path should be accessible within the container.
# For example, if you mount a volume to /shared_data in your Docker Compose,
WAIT_FILE_PATH="/gluetun/forwarded_port"
CHECK_INTERVAL=10 # Seconds to wait between checks

echo "--- Custom Startup Script Initialized ---"
echo "Waiting for file: ${WAIT_FILE_PATH}"

# --- Wait Loop ---
# Loop until the specified file exists.
while [ ! -f "${WAIT_FILE_PATH}" ]; do
  echo "File '${WAIT_FILE_PATH}' not found. Waiting for ${CHECK_INTERVAL} seconds..."
  sleep "${CHECK_INTERVAL}"
done

listen_port=$(</gluetun/forwarded_port)
export FORWARD_PORT=$listen_port
echo "File '${WAIT_FILE_PATH}' found."
echo "Proceeding to start Nicotine+..."

# --- Execute Original Container Process ---
exec init.sh
```

Docker compose file with gluetun and this container
```
services: 
  nicotineplus-proper:
    image: 'sirjmann92/nicotineplus-proper:test'
    container_name: nicotine
    network_mode: "container:gluetun-nicotine" # Comment this line out if you're NOT using a VPN container
#   ports: # Comment this line out if you ARE using a VPN container (line above)
#     - '6565:6565' # Comment this line out if you ARE using a VPN container (lines above)
#     - '2234:2234' # Comment this line out if you ARE using a VPN container (lines above)
#  env_file: .env # Optionally use a .env file to store environment variables and login credentials
    environment: # All environment variables are optional, use as needed, defaults are listed (TZ, LANG, and UMASK have no default)
      - LANG=C.UTF-8
      - UMASK=022
      - DARKMODE=True
      - LOGIN=redacted
      - 'PASSW=redacted'
      - PUID=1000
      - PGID=1000
      - TZ=Mars/Milkyway
      - UPNP=False 
      - AUTO_CONNECT=True
      - TRAY_ICON=False
      - NOTIFY_FILE=False
      - NOTIFY_FOLDER=False
      - NOTIFY_TITLE=False
      - NOTIFY_PM=True
      - NOTIFY_CHATROOM=True
      - NOTIFY_MENTION=True
#     - WEB_UI_PORT=6565 # for custom webUI port assignment. Should match 'port' env variable or VPN webUI port
    volumes:
     # map the custom entry point script
      - ./custom-entrypoint.sh:/custom-entrypoint.sh
      - /mnt/media/downloads/nicotine:/downloads
      - /mnt/media/shared:/shared
      - ./config:/config # Save your config persistently
      - ./data:/data # Store your logs, database, and history
      # map your gluetun directory that has the forwarded_ports file
      - ./gluetun:/gluetun
    entrypoint: /custom-entrypoint.sh
    restart: unless-stopped
    depends_on:
      gluetun-nicotine:
        condition: service_healthy
  gluetun-nicotine:
    image: qmcgaw/gluetun
    container_name: gluetun-nicotine
    cap_add:
      - NET_ADMIN
    networks:
      - outbound
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
#      - 8888:8888/tcp # HTTP proxy
#      - 8388:8388/tcp # Shadowsocks
#      - 8388:8388/udp # Shadowsocks
      # nicotine+ ports
      - 6565:6565
    restart: unless-stopped
    volumes:
      - ./gluetun:/tmp/gluetun
    # healthcheck may be superfluous as I check for this file in my entrypoint script
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/gluetun/forwarded_port"]
      interval: 15s
      start_period: 20s
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=redacted
      - OPENVPN_USER=redacted
      - VPN_PORT_FORWARDING=on
      - OPENVPN_PASSWORD=redacted
      # Timezone for accurate log times
      - TZ=Mars/Milkyway
      - FIREWALL_VPN_INPUT_PORTS_FILE=/tmp/gluetun/forwarded_port

networks:
  outbound:
    external: true
```
I think that is everything.
